### ISSUE TITLE
Cannot resolve dependencies for reug:scalikejackson-macro_2.12:0.5.1

### ISSUE THREAD

**Issue by plokhotnyuk** [reugn/scalikejackson#8]
After adding of the following build configuration:
```
resolvers += Resolver.bintrayRepo("reug", "maven"),
libraryDependencies += "reug" %% "scalikejackson" % "0.5.1"
```

Got an error during refreshing of the sbt build:
```
[warn] ==== bintray-reug-maven: tried
[warn]   https://dl.bintray.com/reug/maven/reug/scalikejackson-macro_2.12/0.5.1/scalikejackson-macro_2.12-0.5.1.pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: reug#scalikejackson-macro_2.12;0.5.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		reug:scalikejackson-macro_2.12:0.5.1 (/home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/build.sbt#L148)
[warn] 		  +- reug:scalikejackson_2.12:0.5.1 (/home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/build.sbt#L148)
[warn] 		  +- com.github.plokhotnyuk.jsoniter-scala:jsoniter-scala-benchmark_2.12:0.50.1-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: reug#scalikejackson-macro_2.12;0.5.1: not found
```

**Comment by reugn** [comment]
Thanks for pointing this out. FIxed in v0.5.2.

**Comment by plokhotnyuk** [comment]
@reugn you are welcome

BTW, would you like try the scalikejackson library in [this contest for JSON parsers](https://plokhotnyuk.github.io/jsoniter-scala/)?

**Comment by reugn** [comment]
Great summary. Sure why not.

**Comment by plokhotnyuk** [comment]
Awesome! Feel free to review and add more: https://github.com/plokhotnyuk/jsoniter-scala/commit/dd14581b37117791ea19afda9895e846c6edebaf

The main value would be not just a feedback in scores but using it as a tool for improving your library.

**Comment by plokhotnyuk** [comment]
I have published [updated results of benchmarks with ScalikeJackson](https://plokhotnyuk.github.io/jsoniter-scala/).

Some of cases are missing because of don't know how or were commented because of failed tests for benchmarks (you can spot them by looking for "FIXME: ScalikeJackson" in sources).
